import { act, cleanup, render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, expect, test, vi } from 'vitest'
import ProjectWorkspace from '../../features/projects/ProjectWorkspace'
import { summaryFixture } from '../fixtures/summaryFixture'

afterEach(() => { cleanup(); vi.unstubAllGlobals(); window.history.replaceState(null, '', '/') })

function setup() {
  vi.stubGlobal('fetch', vi.fn(async () => Response.json({ items: [], total: 0, page: 1, page_size: 5 })))
  render(<ProjectWorkspace />)
  return userEvent.setup()
}

test('opens creation from navigation, traps keyboard focus and restores the draft after Escape', async () => {
  const user = setup()
  const trigger = await screen.findByRole('button', { name: '新建研究项目' })
  await user.click(trigger)
  expect(screen.getByRole('dialog', { name: '新建项目' })).toBeTruthy()
  const name = screen.getByLabelText('项目名称')
  expect(document.activeElement).toBe(name)
  await user.type(name, '待完善的研究')
  await user.keyboard('{Shift>}{Tab}{/Shift}')
  expect(document.activeElement).toBe(screen.getByRole('button', { name: '取消创建' }))
  await user.click(screen.getByRole('heading', { name: '新建项目' }))
  expect(document.activeElement).toBe(screen.getByRole('dialog', { name: '新建项目' }))
  await user.tab({ shift: true })
  expect(document.activeElement).toBe(screen.getByRole('button', { name: '取消创建' }))
  await user.tab()
  expect(document.activeElement).toBe(name)
  await user.keyboard('{Escape}')
  expect(screen.queryByRole('dialog')).toBeNull()
  expect(document.activeElement).toBe(trigger)
  await user.click(trigger)
  expect((screen.getByLabelText('项目名称') as HTMLInputElement).value).toBe('待完善的研究')
})

test('keeps navigation and the list search draft when collapsing and expanding the sidebar', async () => {
  const user = setup()
  await screen.findByText('还没有项目，请先创建一个项目。')
  await user.type(screen.getByLabelText('搜索项目名称'), '尚未提交的搜索')
  const listRequests = () => vi.mocked(fetch).mock.calls.filter(([url]) => String(url).includes('/api/v1/projects?'))
  expect(listRequests()).toHaveLength(1)
  const collapse = screen.getByRole('button', { name: '收起侧边栏' })
  expect(collapse.getAttribute('aria-expanded')).toBe('true')
  await user.click(collapse)
  expect(screen.getByRole('button', { name: '展开侧边栏' }).getAttribute('aria-expanded')).toBe('false')
  await user.click(screen.getByRole('button', { name: '我的项目' }))
  expect(screen.getByRole('button', { name: '我的项目' }).getAttribute('aria-current')).toBe('page')
  await user.click(screen.getByRole('button', { name: '工作台' }))
  expect(screen.getByRole('button', { name: '工作台' }).getAttribute('aria-current')).toBe('page')
  expect((screen.getByLabelText('搜索项目名称') as HTMLInputElement).value).toBe('尚未提交的搜索')
  await user.click(screen.getByRole('button', { name: '展开侧边栏' }))
  expect(screen.getByRole('button', { name: '收起侧边栏' }).getAttribute('aria-expanded')).toBe('true')
  expect((screen.getByLabelText('搜索项目名称') as HTMLInputElement).value).toBe('尚未提交的搜索')
  expect(listRequests()).toHaveLength(1)
})

test('keeps focus inside the creation dialog while the request is pending', async () => {
  const user = setup()
  let finish!: (response: Response) => void
  await screen.findByText('还没有项目，请先创建一个项目。')
  vi.stubGlobal('fetch', vi.fn(() => new Promise<Response>(resolve => { finish = resolve })))
  await user.click(screen.getByRole('button', { name: '新建研究项目' }))
  await user.type(screen.getByLabelText('项目名称'), '焦点测试')
  await user.type(screen.getByLabelText('研究主题'), '科研主题')
  await user.selectOptions(screen.getByLabelText('项目类型'), 'sci')
  await user.click(screen.getByRole('button', { name: '创建项目' }))
  const dialog = screen.getByRole('dialog', { name: '新建项目' })
  expect(document.activeElement).toBe(dialog)
  await user.tab()
  expect(document.activeElement).toBe(dialog)
  await user.keyboard('{Escape}')
  expect(screen.getByRole('dialog')).toBe(dialog)
  await act(async () => finish(new Response(null, { status: 500 })))
  expect(document.activeElement).toBe(screen.getByLabelText('项目名称'))
})

test('moves focus out of hidden project sections and retains an editing draft across navigation', async () => {
  const scrollTo = vi.fn()
  vi.stubGlobal('scrollTo', scrollTo)
  vi.stubGlobal('scrollY', 500)
  const project = { id: 'private-project-id', name: '临床研究', research_topic: '组间比较', project_type: 'sci', file_count: 0,
    created_at: '2026-10-07T00:00:00Z', updated_at: '2026-10-07T00:00:00Z' }
  const fetcher = vi.fn(async (url: string) => {
    if (url.includes('/summary?')) return Response.json(summaryFixture(project.id))
    if (url.endsWith('/files')) return Response.json([])
    if (url.endsWith('/config')) return Response.json({ max_upload_bytes: 10485760, preview_row_limit: 20 })
    if (url === `/api/v1/projects/${project.id}`) return Response.json(project)
    return Response.json({ items: [project], total: 1, page: 1, page_size: 5 })
  })
  vi.stubGlobal('fetch', fetcher)
  const user = userEvent.setup()
  render(<ProjectWorkspace />)
  await user.click(await screen.findByRole('button', { name: '打开项目 临床研究' }))
  await user.click(await screen.findByRole('button', { name: '编辑项目信息' }))
  await user.type(screen.getByLabelText('修改项目名称'), '草稿')
  scrollTo.mockClear()
  await user.click(screen.getByRole('button', { name: /整理研究资料/ }))
  const region = screen.getByRole('region', { name: '当前项目工作区' })
  expect(document.activeElement).toBe(region)
  expect(scrollTo).toHaveBeenCalledWith({ top: 0, behavior: 'instant' })
  expect(screen.queryByRole('button', { name: '保存修改' })).toBeNull()
  expect(screen.getByRole('button', { name: '上传并预览' })).toBeTruthy()
  await user.click(screen.getByRole('button', { name: '数据分析' }))
  await user.click(screen.getByRole('button', { name: '数据' }))
  expect(document.activeElement).toBe(region)
  await user.click(screen.getByRole('button', { name: '我的项目' }))
  expect(screen.queryByRole('region', { name: '当前项目工作区' })).toBeNull()
  await user.click(screen.getByRole('button', { name: '项目概览' }))
  expect((screen.getByRole('textbox', { name: '修改项目名称' }) as HTMLInputElement).value).toBe('临床研究草稿')
  await user.click(screen.getByRole('button', { name: '项目概览' }))
  expect(document.activeElement).toBe(region)
  expect(fetcher.mock.calls.filter(([url]) => url === `/api/v1/projects/${project.id}/files`)).toHaveLength(1)
  expect(document.body.textContent).not.toContain('private-project-id')
  await user.click(screen.getByRole('button', { name: '图表与报告' }))
  await screen.findByText('还没有已生成的 PNG 或 Word 文件。')
  const summaryReads = fetcher.mock.calls.filter(([url]) => url.includes('/summary?')).length
  await user.click(screen.getByRole('button', { name: '我的项目' }))
  await user.click(screen.getByRole('button', { name: '图表与报告' }))
  await screen.findByText('还没有已生成的 PNG 或 Word 文件。')
  expect(fetcher.mock.calls.filter(([url]) => url.includes('/summary?'))).toHaveLength(summaryReads + 1)
})
